# This is a basic workflow to help you get started with Actions

name: Changelog Updater

# Controls when the workflow will run
on:
  pull_request:
    types: 
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-changelog:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        if: github.event.pull_request.merged == true
        run: |
          cat $github_event_path
